name = "SNSensitivityEstimate"
uuid = "4337d2dd-53cf-40a5-bc43-6e7cc5722bd2"
authors = ["Maros Petro"]
version = "1.0.0-DEV"

[deps]
BAT = "c0cd4b16-88b7-57fa-983b-ab80aecada7e"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FHist = "68837c9b-b678-4cd5-9925-8a54edc8f695"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
UnROOT = "3cd96dde-e98d-4713-81e9-a4a1b0235ce9"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
