[deps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FHist = "68837c9b-b678-4cd5-9925-8a54edc8f695"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
SNSensitivityEstimate = "4337d2dd-53cf-40a5-bc43-6e7cc5722bd2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
UnROOT = "3cd96dde-e98d-4713-81e9-a4a1b0235ce9"
